.PHONY: clean All

All:
	@echo "----------Building project:[ aa - Debug ]----------"
	@cd "aa" && "$(MAKE)" -f  "aa.mk"
clean:
	@echo "----------Cleaning project:[ aa - Debug ]----------"
	@cd "aa" && "$(MAKE)" -f  "aa.mk" clean
